language: erlang
otp_release:
  - 17.1
before_install:
  - git clone https://github.com/elixir-lang/elixir
  - cd elixir && make && cd ..
before_script:
  - export PATH=`pwd`/elixir/bin:$PATH
  - mix local.hex --force
  - mix deps.get --only test
script: mix test
after_success:
  - mix coveralls.travis
